### ISSUE TITLE
Advanced bans Support

### ISSUE THREAD

**Issue by BlakeOO2** [samerton/Nameless-Infractions#26]
When I try to hook a MySql data base up to the site it gives this error:

Error:
SQLSTATE[HY000] [2002] Connection refused
Please check your database connection settings.

The data base is hosted with https://www.freemysqlhosting.net

**Comment by samerton** [comment]
Either the MySQL database IP address or port combination is incorrect, or there is a firewall blocking the connection.

AdvancedBan should be using the same connection, and if it connects fine then there might be a problem with your web host preventing the connection.

You can check in the file **modules/Infractions/config.php** to verify the database details are correct, and if so you can ask either your MySQL host or your web host for help, as the problem is with the connection between the two.

**Comment by samerton** [comment]
I'll mark this as closed but if you're still experiencing issues feel free to re-open.
